name: Norminette Check

on:
  pull_request:
    branches:
      - main

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Norminette
        run: |
          pip install norminette

      - name: Run Norminette
        run: |
          norminette . > norminette_output.txt || true
          cat norminette_output.txt
